// <auto-generated />
using DoctorManagement.EntityData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoctorManagement.Migrations
{
    [DbContext(typeof(DoctorContext))]
    [Migration("20220731200730__doctorContext")]
    partial class _doctorContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoctorManagement.Model.DoctorDescription", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BloodGroup")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DoctorType")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmailID")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PatientApppointmentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Technician")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("gender")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("patientName")
                        .HasColumnType("varchar(200)");

                    b.HasKey("ID");

                    b.ToTable("_doctorContext");
                });
#pragma warning restore 612, 618
        }
    }
}
